### ISSUE TITLE
Uploaded Logo from Admin-->Theming not used

### ISSUE THREAD

**Issue by Tanarri** [nextcloud/templateeditor#18]
Hi there,

in the admin settings you can upload on the page "theming" a own logo. This logo is shown on the login page of NextCloud 11.
This uploaded logo should be used, when the system is mailing a share notification to a user by email.

The share email can be customized in admin setting -> mail templates -> template "Sharing email - public link shares (HTML)"
`<td colspan="2" bgcolor="<?php p($theme->getMailHeaderColor());?>">
						<img src="<?php p(\OC::$server->getURLGenerator()->getAbsoluteURL(image_path('', 'logo-mail.png'))); ?>" alt="<?php p($theme->getName()); ?>"/>
					</td>`

I think the image path sould be something else... 
Can someone fix this, that the default template for "Sharing email - public link shares (HTML)" uses the logo from the admin settings --> theming --> logo?

Greetings
Eugen

**Comment by nickvergessen** [comment]
Just use:
```
<td colspan="2" bgcolor="<?php p($theme->getMailHeaderColor());?>"> <img src="<?php p(\OC::$server->getURLGenerator()->getAbsoluteURL($theme->getLogo())); ?>" alt="<?php p($theme->getName()); ?>"/> </td>
```

**Comment by Tanarri** [comment]
This doesn'T fix my issue. 
The lgo ist still the logo from nextcloud and not the logo I have uploaded in admin --> theming

The generated HTML code from the Email ist:
```
				<tr>
					<td colspan="2" bgcolor="#009966">
						<img src="https://myowncloud.uma-pen.com/core/img/logo-mail.png" alt="uma"/>
					</td>
				</tr>
```

"/core/img/logo-mail.png" ist not the logo I have uploaded..

Greetings
Eugen

**Comment by MorrisJobke** [comment]
With the new theming this works now automatically - see https://github.com/nextcloud/server/issues/8350#issuecomment-373837526 if you want to theme with 12+ because this app is not supported there anymore.
